### ISSUE TITLE
Don't pass the parent ID in a nested resource create

### ISSUE THREAD

**Issue by nikkypx** [nikkypx/her#14]
Is there any way to influence Her to not pass the parent ID, when performing a create of the nested resource.

Given the code:
```ruby
  it 'creates a member successfully' do
    @group = Group.find('tstream:Canary-UI_Discuss')
    member = @group.members.create({"id"=>"tt3683", "kind"=>"person"})
  end
```
Her generates

```yaml
- request:
    method: put
    uri: http://IDP:IDP@t1idp1m1.bhdc.att.com:8082/activitystream/v4/groups/tstream:Canary-UI_Discuss/members/tt3683
    body:
      encoding: UTF-8
      string: '{"member":{"id":"tt3683","kind":"person","group_id":"tstream:Canary-UI_Discuss"}}'
    headers:
      User-Agent:
      - Faraday v0.8.8
      Content-Type:
      - application/json
      Accept:
      - '*/*'
```

I would like to eliminate the `group_id` from the body as the server rejects it as an invalid field.

I've tried setting the value to nil in a before_create, but this did not influence the result.
